name: Deploy to Azure VM

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Copy files to VM via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: vmadmin
        key: ${{ secrets.VM_SSH_KEY }}
        source: "index.php"
        target: "/home/vmadmin"

    - name: Deploy file, Remove index.html, and Restart
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: vmadmin
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          sudo rm -f /var/www/html/index.php # Xóa file .php cũ (nếu có)
          sudo rm -f /var/www/html/index.html # <-- LỆNH QUAN TRỌNG: XÓA FILE .HTML
          sudo mv /home/vmadmin/index.php /var/www/html/index.php # Di chuyển file .php mới vào
          sudo chown www-data:www-data /var/www/html/index.php
          sudo systemctl restart apache2
