name: Deploy to Azure VM

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Copy files to VM via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: vmadmin
        key: ${{ secrets.VM_SSH_KEY }}
        source: "index.php"
        target: "/home/vmadmin" # Vẫn copy vào thư mục home

    - name: Deploy file to the correct website
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: vmadmin
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          # DÒNG QUAN TRỌNG: Cập nhật file ở /var/www/my-website/
          sudo rm -f /var/www/my-website/index.php
          sudo mv /home/vmadmin/index.php /var/www/my-website/index.php
          
          # Cấp quyền cho file mới
          sudo chown www-data:www-data /var/www/my-website/index.php
          
          # Xóa file index.html cũ (nếu có)
          sudo rm -f /var/www/my-website/index.html
          
          # Khởi động lại Apache
          sudo systemctl restart apache2
