name: Deploy to Azure VM

on:
  push:
    branches: [ master ] # Đã đổi thành "master" cho bạn

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Copy files to VM via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: vmadmin
        key: ${{ secrets.VM_SSH_KEY }}
        source: "index.php"
        target: "/var/www/html/"

    - name: Set permissions and restart Apache
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: vmadmin
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          sudo chown www-data:www-data /var/www/html/index.php
          sudo systemctl restart apache2
