name: Deploy to Azure VM

on:
  push:
    branches: [ master ] # Kích hoạt khi push lên nhánh "main" [cite: 270-271]

jobs:
  deploy:
    [cite_start]runs-on: ubuntu-latest # Chạy trên một máy ảo Ubuntu [cite: 300]
    steps:
    - [cite_start]uses: actions/checkout@v2 # Bước 1: Lấy code về [cite: 302]

    - name: Copy files to VM via SCP 
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VM_HOST }} 
        username: vmadmin # Đảm bảo đây là username của bạn
        key: ${{ secrets.VM_SSH_KEY }} 
        source: "index.php" 
        target: "/var/www/html/" 

    - name: Set permissions and restart Apache 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: vmadmin # Đảm bảo đây là username của bạn
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          sudo chown www-data:www-data /var/www/html/index.php
          sudo systemctl restart apache2
