name: Deploy to Azure VM

on:
  push:
    [cite_start]branches: [ master ] # Bạn đang dùng nhánh "master", hãy đổi [ main ] thành [ master ] nếu cần 

jobs:
  deploy:
    runs-on: ubuntu-latest # Chạy trên một máy ảo Ubuntu
    steps:
    - uses: actions/checkout@v2 # Bước 1: Lấy code về

    - name: Copy files to VM via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: vmadmin # Đảm bảo đây là username của bạn
        key: ${{ secrets.VM_SSH_KEY }}
        source: "index.php"
        target: "/var/www/html/"

    - name: Set permissions and restart Apache
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: vmadmin # Đảm bảo đây là username của bạn
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          sudo chown www-data:www-data /var/www/html/index.php
          sudo systemctl restart apache2
